services:
  - type: web
    name: spendwise-backend
    env: docker
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/spendwise-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://spendwise:spendwise123@cluster0.aem7oyz.mongodb.net/spendwise